name: C/C++ CI Ubuntu 20.04 x86-64 TON Desktop wallet compile

on: [pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
      - name: Check out current repository
        uses: actions/checkout@v2   
        with:
          path: wallet-desktop
      - name: Compile linux desktop wallet
        run: |
          cd wallet-desktop/auto-build/ubuntu-20.04
          sudo chmod +x build-wallet.sh
          sudo ./build-wallet.sh
      - name: Find & copy binaries
        run: |
          mkdir artifacts
          cp wallet-desktop/auto-build/ubuntu-20.04/Wallet artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-linux-desktop-wallet
          path: artifacts